openapi: 3.1.0
info:
  title: Viyana API
  version: 1.0.0
  description: Main API documentation
servers:
  - url: http://localhost:5000/api
    description: Local server
tags:
  - name: Auth
    description: Authentication endpoints
  - name: Admin => Banners
    description: Manage admin banners
  - name: Admin => Messages
    description: Manage admin messages
  - name: Banners
    description: Banners core data
  - name: Messages
    description: Messages send data
