openapi: 3.1.0
info:
  title: Viyana API
  version: 1.0.0
  description: Main API documentation
servers:
  - url: http://localhost:5000/api
    description: Local server
tags:
  - name: Auth
    description: Authentication endpoints
  - name: Admin => Banner
    description: Manage admin banners
  - name: Admin => Category
    description: Manage admin banners
  - name: Admin => Message
    description: Manage admin messages
  - name: Banner
    description: Banners core data
  - name: Category
    description: Categories core data
  - name: Message
    description: Messages send data
